// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvM2P6sfmS7RIVj5BDqSKX_rLRAsISDYs',
    appId: '1:77933769008:web:7b27e1778d632bf70518f5',
    messagingSenderId: '77933769008',
    projectId: 'dev-gloground',
    authDomain: 'dev-gloground.firebaseapp.com',
    storageBucket: 'dev-gloground.appspot.com',
    measurementId: 'G-SN714XN94N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGo-FA4gLNpf1jmQ2iun4bnBo6DS1V3Y',
    appId: '1:77933769008:android:dcebcc33992347af0518f5',
    messagingSenderId: '77933769008',
    projectId: 'dev-gloground',
    storageBucket: 'dev-gloground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG245JgxKmKxEPFFc8Zo8273ZpT7OA1kQ',
    appId: '1:77933769008:ios:9a632859b077c8c90518f5',
    messagingSenderId: '77933769008',
    projectId: 'dev-gloground',
    storageBucket: 'dev-gloground.appspot.com',
    iosClientId: '77933769008-4dpk0o79li0e6lbpvkko9sh0r3la6vth.apps.googleusercontent.com',
    iosBundleId: 'com.example.glozAllClientExample',
  );
}
