// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCAikPZu1eZKziVBRVUmFYHp3CHqrO5A',
    appId: '1:19780090882:web:c32204edb7783ea09afb1b',
    messagingSenderId: '19780090882',
    projectId: 'glocalize',
    authDomain: 'glocalize.firebaseapp.com',
    databaseURL: 'https://glocalize-default-rtdb.firebaseio.com',
    storageBucket: 'glocalize.appspot.com',
    measurementId: 'G-YWTWVCJCF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4QGXBcADV0PBGTGt3Lj2L3OAzYfevX8',
    appId: '1:19780090882:android:38a45200380dc3c39afb1b',
    messagingSenderId: '19780090882',
    projectId: 'glocalize',
    databaseURL: 'https://glocalize-default-rtdb.firebaseio.com',
    storageBucket: 'glocalize.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCup6drDfd9ycPVyFe2DWl2O2jT8ed_pfo',
    appId: '1:19780090882:ios:c3af683c90ddf4399afb1b',
    messagingSenderId: '19780090882',
    projectId: 'glocalize',
    databaseURL: 'https://glocalize-default-rtdb.firebaseio.com',
    storageBucket: 'glocalize.appspot.com',
    androidClientId: '19780090882-3d4ovfc3uq18tpshq085dd70ogh7rpd1.apps.googleusercontent.com',
    iosClientId: '19780090882-knts1i35l4ebgs1so6ai5s65eops04r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.glozAllClientExample',
  );
}
